Override entrypoints in images

diff --git a/check-images b/check-images
--- a/check-images
+++ b/check-images
@@ -18,7 +18,7 @@ echo "Checking images: $images"
 
 for image in $images; do
 	echo "Checking '$image' image..."
-	docker run $image true || (echo "Cannot run '$image' image!"; exit 1)
+	docker run --entrypoint=/bin/sh $image -c true || (echo "Cannot run '$image' image!"; exit 1)
 done
 
 echo "All images are ok: $images"
diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -14,7 +14,10 @@ images="$1"
 echo "docker-available-tools/system-info - data from `date -I`"
 echo "See: https://github.com/rsp/docker-available-tools"
 
+echo -e "Image\tOS"
+echo -e "-----\t--"
 for image in $images; do
-	echo -ne "$image:\t"
-	docker run $image bash -c "cat /etc/*-release | grep PRETTY_NAME | cut -d '\"' -f 2" || echo "ERROR!"
+	echo -ne "$image\t"
+	docker run --entrypoint=/bin/sh $image -c \
+		"cat /etc/*-release | grep PRETTY_NAME | cut -d '\"' -f 2" || echo "ERROR!"
 done
