Add some collected data to readme

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -19,5 +19,6 @@ echo -e "-----\t--"
 for image in $images; do
 	echo -ne "$image\t"
 	docker run --entrypoint=/bin/sh $image -c \
-		"cat /etc/*-release | grep PRETTY_NAME | cut -d '\"' -f 2" || echo "ERROR!"
+		"cat /etc/*-release | grep PRETTY_NAME | cut -d '\"' -f 2" \
+		|| echo "ERROR!"
 done
